title: RuanWenjun
author: Ruan Wenjun
description: 阮文俊的个人博客

highlighter: null
permalink: /:title

url:
baseurl:

# 分页 
paginate: 12
paginate_path: "page:num"

baidu_tongji_id: c1b59fdd06598101f6a058d92fe41554
# Custom options:
# color_scheme: azul|ruby|amber|avocado
# color_scheme: avocado
